sudo: required
dist: xenial
cache: pip
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  # allow failures
  - 'nightly'
  - 'pypy2.7-6.0'
  - 'pypy3.5-6.0'


matrix:
  fast_finish: true
  allow_failures:
    - python: 'nightly'
    - python: 'pypy2.7-6.0'
    - python: 'pypy3.5-6.0'

addons:
  apt:
    packages:
      - texlive-latex-extra
      - texlive-pictures
      - texlive-science
      - texlive-fonts-recommended
      - lmodern
      - ghostscript
      - pgf

install:
  - cat /etc/ImageMagick*/policy.xml
  - sudo sed '/pattern=".*PDF.*"/d' -i /etc/ImageMagick*/policy.xml
  - cat /etc/ImageMagick*/policy.xml
  - pip install 3to2 future
  - pip install codecov
  - 'if [ "$TRAVIS_PYTHON_VERSION" == 3.4 ]; then pip install -e .[all] --upgrade; else pip install -r dev_requirements.txt --upgrade; fi'
script: ./testall.sh
after_script: codecov
