sudo: required
dist: trusty
language: python
python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.5-dev'
  - 'nightly'
  - 'pypy'
  - 'pypy3'

matrix:
  allow_failures:
    - python: '2.6'
    - python: '3.2'
    - python: '3.5-dev'
    - python: 'nightly'
    - python: 'pypy'
    - python: 'pypy3'

addons:
  apt:
    packages:
      - texlive-latex-extra
      - texlive-pictures
      - texlive-science
      - texlive-full

install:
  - pip install 3to2 future
  - pip install -r dev_requirements.txt
script: ./testall.sh
