language: python
python:
    - '2.7'
    - '3.3'
    - '3.4'
before_install:
    - sudo add-apt-repository ppa:texlive-backports/ppa -y
    - sudo apt-get update
install:
    - wget https://launchpad.net/awkwardduet/1.1/1.1a4/+download/awkwardduet-1.1a4.tar.gz
    - tar -xzvf awkwardduet-1.1a4.tar.gz
    - cd awkwardduet-1.1a4
    - sudo apt-get install python3 python3-setuptools
    - sudo python3 setup.py install
    - cd ..
    - ./convert_to_py2.sh
    - pip install -e .[all]
    - sudo apt-get install texlive-latex-extra texlive-pictures texlive-science
script: ./testall.sh
