sudo: required
dist: trusty
language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.5-dev'
  - 'nightly'

matrix:
  allow_failures:
    - python: '3.5-dev'
    - python: 'nightly'

addons:
  apt:
    packages:
      - texlive-latex-extra
      - texlive-pictures
      - texlive-science
      - texlive-fonts-recommended

install:
  - pip install 3to2 future
  - pip install -r dev_requirements.txt
script: ./testall.sh
