sudo: required
dist: xenial
cache: pip
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  # allow failures
  - 'nightly'
  - 'pypy'
  - 'pypy3'

matrix:
  fast_finish: true
  allow_failures:
    - python: 'nightly'
    - python: 'pypy'
    - python: 'pypy3'

addons:
  apt:
    packages:
      - texlive-latex-extra
      - texlive-pictures
      - texlive-science
      - texlive-fonts-recommended
      - lmodern
      - ghostscript
      - pgf

install:
  - cat /etc/ImageMagick*/policy.xml
  - sudo sed '/pattern=".*PDF.*"/d' -i /etc/ImageMagick*/policy.xml
  - cat /etc/ImageMagick*/policy.xml
  - pip install 3to2 future
  - pip install codecov
  - 'if [ "$TRAVIS_PYTHON_VERSION" == 3.3 -o "$TRAVIS_PYTHON_VERSION" == 3.4 ]; then pip install -e .[all] --upgrade; else pip install -r dev_requirements.txt --upgrade; fi'
script: ./testall.sh
after_script: codecov
